version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  reviewers:
  - akoliyot
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.1
  - dependency-name: inspectpack
    versions:
    - 4.7.1
  - dependency-name: vue
    versions:
    - 2.6.12
