name: Hello World
description: "Greet someone and record the time"

inputs:
  GITHUB_TOKEN:
    required: true
    description: The token provided by GitHub actions via secrets.GITHUB_TOKEN
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"

output:
  time:
    description: "The time we greeted you"

runs:
  using: "node12"
  main: "dist/index.js"
